"""Email personalisation: one spreadsheet row in, a subject line and a body out.

This is the writing half of the enrichment add-on. It never sends anything --
it fills columns in a sheet and a human decides what to do with them. That
framing is deliberate: the customer keeps the list, the sending tool and the
liability, and we keep the part that is actually hard, which is writing four
hundred emails that each sound like they were written for one person.

Three things break personalisation at scale, and each one has a defence here:

  1. The model answers the request instead of doing the job. "Sure! Here is a
     subject line:" lands in a spreadsheet cell and then goes out in a mail
     merge. The system prompts forbid it and every reply is scrubbed again on
     the way out, because a prompt is a request and a scrubber is a guarantee.
  2. The subject bleeds into the body. A cell reading "Subject: Quick question"
     followed by the email is unusable in any sending tool. Subject and body
     are generated by separate calls by default, and a leading "Subject:" is
     stripped out of the body in BOTH modes.
  3. "Five versions" quietly means one email reworded five times. Each variant
     gets a different written angle and a slightly hotter temperature, so the
     set is actually worth A/B testing.

Cost is the customer's, billed to their own OpenAI key with no markup and no
platform key anywhere in the path, so every function here is stingy with calls
and honest about the bill before a run is started.
"""
import inspect
import json
import re
import time

from app import db

from enrich import core
from enrich.models import DEFAULT_MODEL, EnrichRow, PromptTemplate

MAX_VARIANTS = 12
# 12 variants x (subject + body) is the worst legal case. The ceiling is
# re-checked while generating so a future config bug cannot bill a customer
# for fifty calls on one row.
MAX_CALLS_PER_ROW = 24
RETRY_SLEEP = 2.0          # seconds, after a 429, before the one retry
SUBJECT_LIMIT = 70
DEFAULT_MAX_WORDS = 120
MAX_FACT_CHARS = 2000      # the whole "what we know" block
MAX_FACT_VALUE = 300       # one cell inside it

# Each variant is told to take a different run at the same person. Without
# this, "give me 5" returns the same email with the adjectives swapped.
VARIANT_STEERS = [
    "plain and direct: say why you are writing in the first sentence",
    "lead with the single most specific detail you know about them",
    "open with a real question and keep the whole thing curious",
    "shorter and blunter than feels polite -- cut every warm-up line",
    "warmer and more human, with one line of genuine personality",
    "lead with the outcome they would get, not with what you do",
    "name a frustration that is probably real in their world, then help",
    "one concrete observation about them, then one clear small ask",
    "casual, like a note to a colleague you already know",
    "more formal and respectful, no slang, no contractions",
    "hold the detail back: make the last line the reason to reply",
    "lead with proof -- a comparable customer or a concrete result",
]

_QUOTE_PAIRS = (('"', '"'), ("'", "'"), ("\u201c", "\u201d"),
                ("\u2018", "\u2019"))
_SUBJECT_LINE_RE = re.compile(
    r"^\s*(?:[*_#>\s-]*)subject(?:\s*line)?\s*[:\-\u2013\u2014]\s*(.*)$", re.I)
_BODY_LABEL_RE = re.compile(
    r"^\s*(?:[*_#>\s-]*)(?:body|email|email\s*body|message)\s*[:\-]\s*(.*)$",
    re.I)
# "Sure! Here is the email:" is the single most common way a reply arrives
# with one line too many. The pattern deliberately insists the line both opens
# like an announcement AND names what is being announced, so a real first line
# such as "Here is what I would suggest:" is left alone.
_LEAD_IN_RE = re.compile(
    r"^(?:(?:sure|certainly|of course|absolutely|got it|no problem)"
    r"[!,.\s]*)?"
    r"(?:here(?:'s| is| are)|below (?:is|are)|i(?:'ve| have) "
    r"(?:written|drafted|put together))\b"
    r"[^\n]{0,90}\b(?:email|subject|body|draft|version|message|copy|line)s?\b"
    r"[^\n]{0,40}:\s*$"
    r"|^(?:sure|certainly|of course|absolutely|got it|no problem)[!,.]*\s*$",
    re.I)


# --------------------------------------------------------------- small bits
def _flag(value, default=False):
    """Config comes off an HTML form as well as out of JSON, so a checkbox can
    arrive as True, "on", "true", 1, "" or missing."""
    if value is None or value == "":
        return default
    if isinstance(value, str):
        return value.strip().lower() in ("1", "true", "yes", "on", "y")
    return bool(value)


def _int(value, default, lo, hi):
    """Clamp rather than reject: a config typo should not strand a job."""
    try:
        n = int(float(str(value).strip()))
    except (TypeError, ValueError, AttributeError):
        return default
    return max(lo, min(hi, n))


def _clamp_variants(value):
    return _int(value, 1, 1, MAX_VARIANTS)


def _collapse(text):
    return re.sub(r"\s+", " ", str(text or "")).strip()


def _scrub(text, key):
    """Belt and braces on the one rule that cannot be broken: a customer's
    OpenAI key never reaches a log line, a flash message or a CSV cell."""
    s = str(text or "")
    if key and len(str(key)) >= 8:
        s = s.replace(str(key), "[api key hidden]")
    return s


def _safe_key(settings):
    """The customer's key, or None. Decryption failing is a thing that
    happens (a rotated SECRET_KEY) and it must read as "no key", not as a
    traceback out of a row handler."""
    try:
        return settings.key() if settings is not None else None
    except Exception:
        return None


def _temperature(variant):
    """Later variants run hotter. Angle alone still converges on one voice by
    about variant four; a little extra sampling noise keeps them apart."""
    return round(min(1.15, 0.7 + 0.05 * (max(1, variant) - 1)), 2)


def _accepts_temperature(fn):
    """core.complete pins temperature today. Pass one only if the plumbing in
    front of us takes it, so this stays correct either way instead of
    depending on a change in a file this module does not own."""
    try:
        params = inspect.signature(fn).parameters
    except (TypeError, ValueError):
        return False
    if "temperature" in params:
        return True
    return any(p.kind is inspect.Parameter.VAR_KEYWORD
               for p in params.values())


# ------------------------------------------------------------- reply tidying
def _strip_fences(text):
    t = str(text or "").strip()
    return re.sub(r"^```(?:[A-Za-z0-9]+)?\s*|\s*```$", "", t, flags=re.S).strip()


def _unquote(text):
    """Models love wrapping a subject line in quotes. The quotes then ship."""
    s = str(text or "").strip()
    for a, b in _QUOTE_PAIRS:
        if len(s) >= 2 and s.startswith(a) and s.endswith(b):
            return s[1:-1].strip()
    return s


def _drop_lead_in(text):
    """Remove a conversational first line ("Here is the email:") but only when
    something survives it -- never turn a short real email into nothing."""
    s = str(text or "")
    lines = s.split("\n")
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines) and _LEAD_IN_RE.match(lines[i].strip()):
        rest = "\n".join(lines[i + 1:]).strip()
        if rest:
            return rest
    return s.strip()


def _take_subject(text):
    """A subject-line reply -> one clean line, whatever shape it arrived in."""
    s = _drop_lead_in(_strip_fences(text))
    for raw in s.split("\n"):
        line = raw.strip()
        if not line:
            continue
        m = _SUBJECT_LINE_RE.match(line)
        if m:
            line = m.group(1).strip()
            if not line:
                continue
        return _unquote(_collapse(line))
    return ""


def _clean_body(text):
    """-> (body, lifted_subject).

    Strips any leading "Subject: ..." line off the body and hands it back
    instead of deleting it, because in the one-call mode that line IS the
    subject. The loop repeats: some models emit the label twice.
    """
    s = _drop_lead_in(_strip_fences(text))
    s = s.replace("\r\n", "\n").replace("\r", "\n")
    lifted = ""
    while True:
        lines = s.split("\n")
        i = 0
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i >= len(lines):
            break
        m = _SUBJECT_LINE_RE.match(lines[i].strip())
        if not m:
            break
        if not lifted:
            lifted = _unquote(_collapse(m.group(1)))
        s = "\n".join(lines[i + 1:])
    s = _strip_body_label(s)
    s = re.sub(r"\n{3,}", "\n\n", s).strip()
    return s, lifted


def _strip_body_label(text):
    """Drop a "Body:" / "Email:" label the model added to its own output."""
    lines = str(text or "").split("\n")
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i >= len(lines):
        return str(text or "")
    m = _BODY_LABEL_RE.match(lines[i].strip())
    if not m:
        return str(text or "")
    rest = m.group(1).strip()
    tail = "\n".join(lines[i + 1:])
    return (rest + "\n" + tail) if rest else tail


def _pick(data, *names):
    """Case-insensitive key lookup; models return Subject, subject or SUBJECT."""
    if not isinstance(data, dict):
        return ""
    lowered = {str(k).strip().lower(): v for k, v in data.items()}
    for n in names:
        v = lowered.get(n.lower())
        if v not in (None, ""):
            return v if isinstance(v, str) else str(v)
    return ""


def _split_reply(text):
    """A non-JSON single-call reply -> (subject, body, note).

    Order matters and is the whole fallback ladder: a leading "Subject:" line
    is a real subject, and anything else is an email with no subject, which is
    still worth handing back -- a blank cell is a problem the customer can see
    and fix, an exception is a row they lose.
    """
    body, lifted = _clean_body(text)
    if lifted:
        return lifted, body, ""
    if not body:
        return "", "", "The model returned nothing usable."
    return "", body, ("No subject line came back -- the whole reply is in the "
                      "email column.")


# --------------------------------------------------------------- the prompts
def _facts(row_data):
    """A compact "what we know" block.

    The customer's prompt only mentions the columns they thought to reference.
    Handing the model the rest of the row, labelled and bounded, is what lets
    the "lead with the specific detail" variant find a detail at all. It is
    capped because the customer pays for every character of it.
    """
    lines, used = [], 0
    for key, value in (row_data or {}).items():
        v = _collapse(value)
        if not v:
            continue
        if len(v) > MAX_FACT_VALUE:
            v = v[:MAX_FACT_VALUE].rstrip() + "..."
        line = f"{_collapse(key)}: {v}"
        if used + len(line) > MAX_FACT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)


def _instructions(config, row_data, kind):
    """-> (text, missing). The customer's own prompt with {Column} tokens
    filled from this row by core.fill, which is also what reports the tokens
    it could not resolve."""
    cfg = config or {}
    body = str(cfg.get("body_prompt") or "").strip()
    subject = str(cfg.get("subject_prompt") or "").strip()
    if kind == "subject":
        template = subject or (
            "Write only the subject line for the email described here.\n\n"
            + body)
    elif kind == "body":
        template = body
    else:
        template = body
        if subject:
            template = ("EMAIL BODY INSTRUCTIONS\n" + body
                        + "\n\nSUBJECT LINE INSTRUCTIONS\n" + subject)
    return core.fill(template, row_data or {})


def missing_columns(config, row_data):
    """Token names the customer's prompts use that this row cannot fill.

    Not fatal on purpose: one blank cell in row 300 should cost that row a
    weaker email, not the run. The names are recorded on the row so the
    customer can see exactly which sheet column let them down.
    """
    seen, out = set(), []
    for kind in ("subject", "body"):
        _, missing = _instructions(config, row_data, kind)
        for name in missing:
            if name not in seen:
                seen.add(name)
                out.append(name)
    return out


def _shape_rules(kind, max_words):
    """The rules that have actually broken for this owner, stated as rules."""
    common = [
        "OUTPUT SHAPE -- this matters more than the writing:",
        "No preamble, no explanation, no commentary, no alternatives.",
        "Never write \"Here is\", \"Sure\", \"I hope this helps\" or anything "
        "about yourself.",
        "No markdown, no asterisks, no headings, no bullets, no code fences.",
        "No emoji, ever.",
    ]
    if kind == "subject":
        return common + [
            "Return the subject line and nothing else.",
            f"One line, under {SUBJECT_LIMIT} characters.",
            "No \"Subject:\" label and no quotation marks around it.",
            "Sentence case. No clickbait, no ALL CAPS, no exclamation marks.",
        ]
    if kind == "body":
        return common + [
            "Return the email body and nothing else.",
            f"Plain text, under {max_words} words.",
            "Short paragraphs, one to three sentences each, with a blank line "
            "between them.",
            "Do not write a subject line. Do not start with \"Subject:\".",
            "Do not add a sign-off, a name or a signature block unless the "
            "instructions below ask for one.",
        ]
    return common + [
        "Return one JSON object and nothing else, with exactly two string "
        "keys: \"subject\" and \"body\".",
        f"\"subject\": one line, under {SUBJECT_LIMIT} characters, sentence "
        "case, no quotation marks, no clickbait.",
        f"\"body\": the email as plain text, under {max_words} words, short "
        "paragraphs separated by blank lines.",
        "The body must NOT contain a subject line and must not begin with "
        "\"Subject:\". The subject belongs in the subject key only.",
        "Do not add a sign-off, a name or a signature block unless the "
        "instructions below ask for one.",
    ]


def build_messages(config, row_data, kind):
    """-> (system, user) for one completion.

    kind is "subject" or "body" for the two-call mode, or "both" for the
    single-call JSON mode. The variant steer rides in config as "variant" and
    "variant_count" so this stays a plain function of (config, row, kind) and
    can be asserted on in a test without a model anywhere near it.

    The system message carries the rules and the shape; the user message
    carries this one person. Keeping them apart is why the shape rules survive
    a customer prompt that says something careless like "reply with a few
    options".
    """
    cfg = config or {}
    row_data = row_data or {}
    max_words = _int(cfg.get("max_words"), DEFAULT_MAX_WORDS, 10, 1000)
    tone = _collapse(cfg.get("tone"))
    sender = _collapse(cfg.get("sender_name"))
    company = _collapse(cfg.get("sender_company"))
    extra = str(cfg.get("extra_rules") or "").strip()
    variant = _clamp_variants(cfg.get("variant"))
    variant_count = _clamp_variants(cfg.get("variant_count"))

    lines = [
        "You write one-to-one outreach email copy. You are given what is known "
        "about a single person and the sender's own instructions. You write "
        "for that one person and nobody else.",
    ]
    if sender and company:
        lines.append(f"You are writing as {sender} at {company}.")
    elif sender:
        lines.append(f"You are writing as {sender}.")
    elif company:
        lines.append(f"You are writing on behalf of {company}.")
    if tone:
        lines.append(f"Tone: {tone}.")
    lines.append("")
    lines.extend(_shape_rules(kind, max_words))
    lines.append("")
    lines.extend([
        "TRUTH:",
        "Use only the details you are given. Do not invent a mutual contact, a "
        "funding round, a product name, a metric or a compliment you cannot "
        "support.",
        "If a detail is blank, write around it. Never output an empty bracket, "
        "a placeholder such as [Company], or a column name still in braces.",
    ])
    if extra:
        lines.extend(["", "ALSO FROM THE SENDER:", extra])
    if variant_count > 1:
        steer = VARIANT_STEERS[(variant - 1) % len(VARIANT_STEERS)]
        lines.extend([
            "",
            f"This is version {variant} of {variant_count}. Write it "
            f"{steer}.",
            "It must differ from the other versions in angle, opening line and "
            "phrasing -- not just in wording. Do not hedge toward the middle.",
        ])
    system = "\n".join(lines).strip()

    instructions, _ = _instructions(cfg, row_data, kind)
    facts = _facts(row_data)
    parts = []
    if facts:
        parts.append("WHAT WE KNOW ABOUT THIS PERSON\n" + facts)
    parts.append("INSTRUCTIONS FROM THE SENDER\n"
                 + (instructions or "Write a short, relevant outreach email."))
    if kind == "subject":
        parts.append("Now return only the subject line.")
    elif kind == "body":
        parts.append("Now return only the email body.")
    else:
        parts.append("Now return only the JSON object.")
    return system, "\n\n".join(parts)


# ------------------------------------------------------------------ the call
def _call(key, model, system, user, max_tokens, temperature, json_mode=False):
    """One completion, with a single retry on a 429.

    core.complete is looked up on the module at call time rather than imported
    by name: that is what lets a test stub it, and what keeps a key rotation
    or a transport change in core from needing an edit here.
    """
    fn = core.complete
    kwargs = {"max_tokens": max_tokens, "json_mode": json_mode}
    if _accepts_temperature(fn):
        kwargs["temperature"] = temperature
    for attempt in (1, 2):
        try:
            out = fn(key, model, system, user, **kwargs) or {}
        except Exception as e:                      # a vendor library throwing
            return {"ok": False,
                    "error": _scrub(f"{type(e).__name__}: {e}", key)[:200]}
        if out.get("ok") or not out.get("retry") or attempt == 2:
            return out
        time.sleep(RETRY_SLEEP)
    return {"ok": False, "error": "OpenAI did not answer."}


def _body_tokens(max_words):
    """Enough room to finish the email. A body cut off mid-sentence is worse
    than no body at all, because it looks fine in a spreadsheet preview."""
    return max(200, min(1400, int(max_words * 2.2) + 120))


def generate(settings, config, row_data, model, variants=1):
    """Write `variants` versions for one person.

    -> {ok, items:[{variant, subject, body, note}], tokens_in, tokens_out,
        cost, error}

    Two modes, and the split between them is the whole point of this module:

      separate_subject True (the default) runs two calls per variant, one for
        the subject and one for the body. It costs more and it cannot bleed,
        because neither call is ever asked for both.
      separate_subject False runs one JSON call per variant. Cheaper, and it
        degrades through a ladder -- strict JSON, then a leading "Subject:"
        line, then everything into the body with a note -- so a bad reply
        costs a weaker row, never a lost one.

    Partial success is still success: four good versions and one failed call
    returns ok with the four and the reason for the fifth.
    """
    key = _safe_key(settings)
    blank = {"ok": False, "items": [], "tokens_in": 0, "tokens_out": 0,
             "cost": 0.0, "error": ""}
    if not key:
        blank["error"] = "Add your OpenAI key in Settings before running this."
        return blank

    cfg = dict(config or {})
    model = (model or getattr(settings, "default_model", "")
             or DEFAULT_MODEL)
    n = _clamp_variants(variants)
    separate = _flag(cfg.get("separate_subject"), True)
    max_words = _int(cfg.get("max_words"), DEFAULT_MAX_WORDS, 10, 1000)
    per_variant = 2 if separate else 1

    items, errors = [], []
    t_in = t_out = 0
    calls_left = MAX_CALLS_PER_ROW
    for i in range(1, n + 1):
        if calls_left < per_variant:
            errors.append(f"Stopped after {len(items)} version(s): the "
                          f"{MAX_CALLS_PER_ROW}-call limit for one row.")
            break
        calls_left -= per_variant
        cfg_i = dict(cfg, variant=i, variant_count=n)
        temp = _temperature(i)

        if separate:
            sys_s, usr_s = build_messages(cfg_i, row_data, "subject")
            res_s = _call(key, model, sys_s, usr_s, 90, temp)
            sys_b, usr_b = build_messages(cfg_i, row_data, "body")
            res_b = _call(key, model, sys_b, usr_b, _body_tokens(max_words),
                          temp)
            for res in (res_s, res_b):
                t_in += int(res.get("tokens_in") or 0)
                t_out += int(res.get("tokens_out") or 0)
            if not res_s.get("ok") and not res_b.get("ok"):
                errors.append(_scrub(res_b.get("error")
                                     or res_s.get("error")
                                     or "OpenAI call failed.", key))
                continue
            subject = _take_subject(res_s.get("text")) if res_s.get("ok") else ""
            body, lifted = _clean_body(res_b.get("text") or "")
            note = ""
            if not res_s.get("ok"):
                subject = lifted
                note = "Subject call failed: " + _scrub(
                    res_s.get("error") or "no reply", key)
            elif not res_b.get("ok"):
                note = "Email call failed: " + _scrub(
                    res_b.get("error") or "no reply", key)
            elif not subject and lifted:
                subject = lifted
            if not note and body and not subject:
                note = "No subject line came back for this version."
            if not subject and not body:
                errors.append("The model returned nothing usable.")
                continue
            items.append({"variant": i, "subject": subject, "body": body,
                          "note": note})
            continue

        sys_j, usr_j = build_messages(cfg_i, row_data, "both")
        res = _call(key, model, sys_j, usr_j, _body_tokens(max_words) + 90,
                    temp, json_mode=True)
        t_in += int(res.get("tokens_in") or 0)
        t_out += int(res.get("tokens_out") or 0)
        if not res.get("ok"):
            errors.append(_scrub(res.get("error") or "OpenAI call failed.", key))
            continue
        text = res.get("text") or ""
        data = res.get("data")
        if not isinstance(data, dict):
            data = core.parse_json(text)
        note = ""
        if isinstance(data, dict) and (_pick(data, "subject", "subject_line")
                                       or _pick(data, "body", "email")):
            subject = _take_subject(_pick(data, "subject", "subject_line"))
            body, lifted = _clean_body(_pick(data, "body", "email", "message"))
            if not subject and lifted:
                subject = lifted
        else:
            subject, body, note = _split_reply(text)
        if not subject and not body:
            errors.append("The model returned nothing usable.")
            continue
        items.append({"variant": i, "subject": subject, "body": body,
                      "note": note})

    return {"ok": bool(items), "items": items, "tokens_in": t_in,
            "tokens_out": t_out, "cost": core.price(model, t_in, t_out),
            "error": "; ".join(e for e in errors if e)[:400]}


# -------------------------------------------------------------- the row job
def process_row(job, row, settings):
    """Write this row's columns. Never raises -- the runner counts a failed
    row, and a row that raised would take the chunk's commit with it."""
    try:
        config = job.config or {}
        model = job.model or DEFAULT_MODEL
        row_data = row.input or {}
        n = _clamp_variants(config.get("variants"))
        missing = missing_columns(config, row_data)

        res = generate(settings, config, row_data, model, variants=n)
        items = res.get("items") or []

        out = {}
        for i in range(1, n + 1):
            item = items[i - 1] if i - 1 < len(items) else {}
            s_key = "Subject" if n == 1 else f"Subject {i}"
            b_key = "Email" if n == 1 else f"Email {i}"
            out[s_key] = item.get("subject", "")
            out[b_key] = item.get("body", "")

        notes = [it.get("note") for it in items if it.get("note")]
        if items:
            bits = []
            if len(items) < n:
                bits.append(f"{len(items)} of {n} versions written")
            else:
                bits.append("ok")
            if missing:
                bits.append("blank columns: " + ", ".join(missing))
            if notes:
                bits.append("; ".join(dict.fromkeys(notes)))
            if res.get("error"):
                bits.append(res["error"])
            out["Personalize Status"] = " - ".join(bits)[:400]
            row.state = "done"
            row.error = ""
        else:
            msg = res.get("error") or "No email was written for this row."
            out["Personalize Status"] = msg[:400]
            row.state = "failed"
            row.error = msg[:400]

        row.output_json = json.dumps(out)
        row.cost = round(float(res.get("cost") or 0), 6)
        job.tokens_in = (job.tokens_in or 0) + int(res.get("tokens_in") or 0)
        job.tokens_out = (job.tokens_out or 0) + int(res.get("tokens_out") or 0)
    except Exception as e:                           # last line of defence
        msg = _scrub(f"{type(e).__name__}: {e}", _safe_key(settings))[:400]
        row.state = "failed"
        row.error = msg
        row.cost = row.cost or 0.0
        try:
            row.output_json = json.dumps({"Personalize Status": msg})
        except Exception:
            row.output_json = "{}"


# ------------------------------------------------------------- before it runs
def estimate_job(job, settings=None):
    """What the pending rows will cost, before a penny is spent.

    The call count, not the row count, is what surprises people: twelve
    variants with a separate subject is twenty-four calls per row, so five
    thousand rows is a hundred and twenty thousand calls. calls_per_row and
    variants come back so the screen can say that out loud.
    """
    cfg = job.config or {}
    model = (job.model or getattr(settings, "default_model", "")
             or DEFAULT_MODEL)
    variants = _clamp_variants(cfg.get("variants"))
    separate = _flag(cfg.get("separate_subject"), True)
    max_words = _int(cfg.get("max_words"), DEFAULT_MAX_WORDS, 10, 1000)
    per_variant = 2 if separate else 1
    calls_per_row = min(MAX_CALLS_PER_ROW, variants * per_variant)

    sample = []
    try:
        pending = EnrichRow.query.filter_by(job_id=job.id,
                                            state="pending").count()
        sample = (EnrichRow.query.filter_by(job_id=job.id, state="pending")
                  .order_by(EnrichRow.idx).limit(5).all())
    except Exception:
        pending = max(0, (job.total or 0) - (job.done or 0) - (job.failed or 0))

    # Measure a real row rather than guessing: the facts block is usually
    # bigger than the prompt and it is the customer's money.
    sizes = []
    for r in sample:
        s, u = build_messages(dict(cfg, variant=1, variant_count=variants),
                             r.input, "body" if separate else "both")
        sizes.append(len(s) + len(u))
    if not sizes:
        s, u = build_messages(dict(cfg, variant=1, variant_count=variants),
                              {}, "body" if separate else "both")
        sizes.append(len(s) + len(u))
    per_call_chars = int(sum(sizes) / len(sizes))

    # One variant produces a subject (short) plus a body of about max_words.
    out_per_variant = 20 + int(max_words * 1.45)
    est = core.estimate(model, pending,
                        prompt_chars=per_call_chars * calls_per_row,
                        out_tokens=out_per_variant, variants=variants)
    est.update({
        "ok": True,
        "rows": pending,
        "variants": variants,
        "separate_subject": separate,
        "calls_per_row": calls_per_row,
        "calls_total": calls_per_row * pending,
        "per_row_pretty": core.money(est["per_row"]),
        "total_pretty": core.money(est["total"]),
    })
    cap = getattr(settings, "monthly_spend_cap", None)
    if cap:
        spent = float(getattr(settings, "spend_this_month", 0) or 0)
        est["cap_remaining"] = round(max(0.0, float(cap) - spent), 6)
        est["over_cap"] = (spent + est["total"]) > float(cap)
    return est


def validate_config(config, headers):
    """-> {ok, problems, warnings, tokens}

    Run before a job starts, because every one of these mistakes is free to
    fix now and expensive to find in row four hundred of a finished export.
    Problems block the run; warnings are things the customer may well mean.
    """
    cfg = config or {}
    cols = [str(h) for h in (headers or [])]
    problems, warnings = [], []

    body = str(cfg.get("body_prompt") or "").strip()
    subject = str(cfg.get("subject_prompt") or "").strip()
    separate = _flag(cfg.get("separate_subject"), True)
    if not body:
        problems.append("Write the email prompt -- that is the one thing this "
                        "cannot guess.")

    names = []
    for text in (body, subject):
        for name in core.tokens_in_template(text):
            if name not in names:
                names.append(name)
    unknown = [n for n in names if not _matches_column(n, cols)]
    if cols:
        for name in unknown:
            problems.append(f"Your prompt uses {{{name}}}, but there is no "
                            f"column called that in this sheet.")
    elif names:
        warnings.append("No sheet columns were supplied, so the {tokens} in "
                        "the prompt could not be checked.")

    raw_variants = cfg.get("variants", 1)
    if raw_variants not in (None, ""):
        try:
            v = int(float(str(raw_variants).strip()))
        except (TypeError, ValueError):
            problems.append("Versions per row must be a whole number between "
                            f"1 and {MAX_VARIANTS}.")
            v = 1
        if v < 1 or v > MAX_VARIANTS:
            problems.append(f"Versions per row must be between 1 and "
                            f"{MAX_VARIANTS}. You asked for {v}.")
    variants = _clamp_variants(raw_variants)

    raw_words = cfg.get("max_words")
    if raw_words not in (None, ""):
        try:
            w = int(float(str(raw_words).strip()))
        except (TypeError, ValueError):
            problems.append("Maximum words must be a number.")
            w = DEFAULT_MAX_WORDS
        if w < 20:
            problems.append(f"{w} words is not an email. Use 40 or more.")
        elif w > 600:
            problems.append(f"{w} words is a newsletter, not outreach, and it "
                            "will cost accordingly. Use 300 or fewer.")

    if body and not names:
        warnings.append("This prompt has no {Column} tokens, so every row "
                        "gets the same email. That is a mail merge with extra "
                        "steps -- add a token like {First Name} or {Company}.")
    if len(body) + len(subject) > 6000:
        warnings.append("That is a very long prompt. It is re-sent on every "
                        "call, so it is paid for on every row.")
    if not separate and variants >= 6:
        warnings.append(f"{variants} versions from a single call each tends to "
                        "produce one email reworded. Turn the separate subject "
                        "line back on for a real spread.")
    if separate and not subject:
        warnings.append("No subject prompt, so the subject line will be "
                        "written from the email prompt.")

    return {"ok": not problems, "problems": problems, "warnings": warnings,
            "tokens": names, "unknown_tokens": unknown}


def _matches_column(name, headers):
    """Same loose matching core.fill does, so validation agrees with reality:
    case, title case and stray spaces all still resolve."""
    want = str(name).strip()
    squashed = want.lower().replace(" ", "")
    for h in headers:
        if h == want or h.lower() == want.lower():
            return True
        if h.lower().replace(" ", "") == squashed:
            return True
    return False


# ------------------------------------------------------------------ templates
# PromptTemplate has no free-form column, so sender name, sender company and
# extra rules cannot be stored with a template. They are reported back rather
# than dropped quietly, because a template that silently loses a rule is worse
# than one that admits it.
TEMPLATE_FIELDS = ("subject_prompt", "body_prompt", "separate_subject",
                   "variants", "tone", "max_words")
UNSAVED_FIELDS = ("sender_name", "sender_company", "extra_rules")


def save_template(account_id, name, config, model=None, template_id=None):
    """-> {ok, id, name, not_saved, error}. Upserts on name, so saving the
    same template twice edits it instead of breeding "Cold outreach (2)"."""
    cfg = config or {}
    name = _collapse(name)[:200]
    if not name:
        return {"ok": False, "error": "Give the template a name."}
    try:
        row = None
        if template_id:
            row = PromptTemplate.query.filter_by(
                id=template_id, account_id=account_id).first()
        if row is None:
            row = PromptTemplate.query.filter_by(
                account_id=account_id, name=name, kind="personalize").first()
        if row is None:
            row = PromptTemplate(account_id=account_id, name=name,
                                 kind="personalize")
            db.session.add(row)
        row.name = name
        row.subject_prompt = str(cfg.get("subject_prompt") or "")
        row.body_prompt = str(cfg.get("body_prompt") or "")
        row.separate_subject = _flag(cfg.get("separate_subject"), True)
        row.variants = _clamp_variants(cfg.get("variants"))
        row.tone = _collapse(cfg.get("tone"))[:200]
        row.max_words = _int(cfg.get("max_words"), DEFAULT_MAX_WORDS, 10, 1000)
        # Only move the model when a model was actually chosen: re-saving a
        # prompt edit must not quietly demote a template from gpt-4.1 back to
        # the default and halve the writing quality on the next run.
        chosen = model or cfg.get("model") or row.model or DEFAULT_MODEL
        row.model = str(chosen)[:60]
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        return {"ok": False, "error": f"Could not save that template "
                                      f"({type(e).__name__})."}
    return {"ok": True, "id": row.id, "name": row.name, "model": row.model,
            "not_saved": [f for f in UNSAVED_FIELDS if cfg.get(f)]}


def load_template(account_id, template_id):
    """-> {ok, id, name, model, config, not_saved, error}. The config comes
    back in exactly the shape generate() and process_row() expect."""
    try:
        row = PromptTemplate.query.filter_by(
            id=template_id, account_id=account_id).first()
    except Exception as e:
        return {"ok": False, "error": f"Could not read that template "
                                      f"({type(e).__name__})."}
    if row is None:
        return {"ok": False, "error": "That saved prompt is no longer there."}
    return {"ok": True, "id": row.id, "name": row.name,
            "model": row.model or DEFAULT_MODEL,
            "config": {"subject_prompt": row.subject_prompt or "",
                       "body_prompt": row.body_prompt or "",
                       "separate_subject": bool(row.separate_subject),
                       "variants": _clamp_variants(row.variants),
                       "tone": row.tone or "",
                       "max_words": _int(row.max_words, DEFAULT_MAX_WORDS,
                                         10, 1000)},
            "not_saved": list(UNSAVED_FIELDS)}


def list_templates(account_id):
    """Name and id only -- enough to populate a picker without loading every
    prompt body into a page."""
    try:
        rows = (PromptTemplate.query
                .filter_by(account_id=account_id, kind="personalize")
                .order_by(PromptTemplate.name).all())
    except Exception:
        return []
    return [{"id": r.id, "name": r.name, "model": r.model or DEFAULT_MODEL,
             "variants": r.variants or 1,
             "separate_subject": bool(r.separate_subject)} for r in rows]
